import { useEffect, useState, useCallback, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Download, Trash2, Loader2, FileDown, TrendingUp } from "lucide-react";
import { format } from "date-fns";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, CartesianGrid } from "recharts";
import { CATEGORIES, Manufacturer, REPORT_TYPE_LABELS, ReportSnapshot, api, fmt } from "../shared";

export function ReportsTab() {
  const [reports, setReports] = useState<ReportSnapshot[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selectedReport, setSelectedReport] = useState<ReportSnapshot | null>(null);
  const [downloadingId, setDownloadingId] = useState<number | null>(null);
  const [deletingId, setDeletingId] = useState<number | null>(null);
  const reportPreviewRef = useRef<HTMLDivElement>(null);

  const [filterType, setFilterType] = useState<"weekly" | "monthly" | "custom">("monthly");
  const [filterDateFrom, setFilterDateFrom] = useState(() => {
    const d = new Date();
    d.setMonth(d.getMonth() - 1);
    return d.toISOString().slice(0, 10);
  });
  const [filterDateTo, setFilterDateTo] = useState(() => new Date().toISOString().slice(0, 10));
  const [filterCategory, setFilterCategory] = useState("");
  const [filterOperator, setFilterOperator] = useState("");
  const [filterRegion, setFilterRegion] = useState("");
  const [filterManufacturer, setFilterManufacturer] = useState("");
  const [filterProductType, setFilterProductType] = useState("");
  const [filterListingType, setFilterListingType] = useState("");
  const [sortField, setSortField] = useState<"date" | "type">("date");
  const [sortDir, setSortDir] = useState<"desc" | "asc">("desc");

  const loadReports = useCallback(() => {
    setLoading(true);
    api("/admin/reports")
      .then(setReports)
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => { loadReports(); }, [loadReports]);

  const generateReport = async () => {
    setGenerating(true);
    try {
      const filters: Record<string, string> = {};
      if (filterCategory) filters.category = filterCategory;
      if (filterOperator) filters.operator = filterOperator;
      if (filterRegion) filters.region = filterRegion;
      if (filterManufacturer) filters.manufacturer = filterManufacturer;
      if (filterProductType) filters.product_type = filterProductType;
      if (filterListingType) filters.listing_type = filterListingType;

      const snap: ReportSnapshot = await api("/admin/reports/generate", "POST", {
        type: filterType,
        date_range_start: filterDateFrom,
        date_range_end: filterDateTo,
        filters: Object.keys(filters).length ? filters : undefined,
      });

      setReports((prev) => [snap, ...prev]);
      setSelectedReport(snap);
    } catch (err) {
      console.error(err);
      alert("Failed to generate report. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  const loadAndView = async (id: number) => {
    try {
      const snap: ReportSnapshot = await api(`/admin/reports/${id}`);
      setSelectedReport(snap);
    } catch (err) {
      console.error(err);
    }
  };

  const fetchAndDownload = async (id: number) => {
    setDownloadingId(id);
    try {
      const snap: ReportSnapshot = await api(`/admin/reports/${id}`);
      setSelectedReport(snap);
      await new Promise<void>((resolve) => {
        requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
      });
      await downloadPDF(snap, false);
    } catch (err) {
      console.error("Fetch and download failed", err);
      alert("Failed to download report. Please try again.");
    } finally {
      setDownloadingId(null);
    }
  };

  const downloadCSV = (report: ReportSnapshot) => {
    const d = report.data_json;
    if (!d) return;

    const rows: string[][] = [];
    const esc = (v: string | number) => {
      const s = String(v);
      return s.includes(",") || s.includes('"') || s.includes("\n")
        ? `"${s.replace(/"/g, '""')}"` : s;
    };
    const row = (...cells: (string | number)[]) => rows.push(cells.map(esc));

    row("LyoDex Market Intelligence Report");
    row("Title", report.title);
    row("Period", `${format(new Date(report.date_range_start), "MMM d, yyyy")} – ${format(new Date(report.date_range_end), "MMM d, yyyy")}`);
    row("Generated by", report.generated_by_email);
    row("Generated at", format(new Date(report.generated_at), "MMM d, yyyy HH:mm"));
    row("");

    if (d.summary) {
      row("Summary");
      row(d.summary);
      row("");
    }

    if (d.sales_volume) {
      row("Sales Volume KPIs");
      row("Metric", "Value");
      row("Total Contracts", d.sales_volume.total_contracts);
      row("Total Volume (kg)", d.sales_volume.total_quantity_kg);
      row("Total Contract Value ($)", d.sales_volume.total_contract_value);
      row("Platform Fees ($)", d.sales_volume.platform_fees);
      row("");
    }

    if (d.avg_price_by_category?.length) {
      row("Avg Price by Category");
      row("Category", "Avg $/kg", "Data Points");
      for (const r of d.avg_price_by_category) row(r.category, r.avg_price, r.count);
      row("");
    }

    if (d.top_materials?.length) {
      row("Top Materials Requested");
      row("Material", "Request Count");
      for (const r of d.top_materials) row(r.name, r.value);
      row("");
    }

    if (d.requests_by_month?.length) {
      row("Requests by Month");
      row("Month", "Request Count");
      for (const r of d.requests_by_month) row(r.month, r.value);
      row("");
    }

    if (d.bids_by_month?.length) {
      row("Bids by Month");
      row("Month", "Bid Count");
      for (const r of d.bids_by_month) row(r.month, r.value);
      row("");
    }

    if (d.revenue_by_month?.length) {
      row("Platform Revenue by Month ($)");
      row("Month", "Revenue ($)");
      for (const r of d.revenue_by_month) row(r.month, r.value);
      row("");
    }

    if (d.operator_win_rates?.length) {
      row("Operator Win Rates");
      row("Operator", "Win Rate (%)");
      for (const r of d.operator_win_rates) row(r.name, r.win_rate);
      row("");
    }

    const csv = rows.map(r => r.join(",")).join("\r\n");
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_${format(new Date(report.generated_at), "yyyy-MM-dd")}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadPDF = async (report: ReportSnapshot, manageLoadingState = true) => {
    if (manageLoadingState) setDownloadingId(report.id);
    try {
      const { default: jsPDF } = await import("jspdf");
      const { default: html2canvas } = await import("html2canvas");

      if (!reportPreviewRef.current) return;

      const canvas = await html2canvas(reportPreviewRef.current, {
        scale: 1.5,
        useCORS: true,
        backgroundColor: "#ffffff",
        logging: false,
      });

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "pt",
        format: "a4",
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 36;
      const imgWidth = pageWidth - 2 * margin;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      let y = margin;
      let remaining = imgHeight;
      let srcY = 0;
      const srcHeight = canvas.height;
      const srcWidth = canvas.width;

      while (remaining > 0) {
        const sliceHeight = Math.min(pageHeight - 2 * margin, remaining);
        const sliceCanvas = document.createElement("canvas");
        sliceCanvas.width = srcWidth;
        sliceCanvas.height = (sliceHeight / imgWidth) * srcWidth;
        const ctx = sliceCanvas.getContext("2d")!;
        ctx.drawImage(canvas, 0, srcY, srcWidth, sliceCanvas.height, 0, 0, srcWidth, sliceCanvas.height);
        const sliceData = sliceCanvas.toDataURL("image/png");
        pdf.addImage(sliceData, "PNG", margin, y, imgWidth, sliceHeight);
        srcY += sliceCanvas.height;
        remaining -= sliceHeight;
        if (remaining > 0) { pdf.addPage(); y = margin; }
      }

      const filename = `${report.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_${format(new Date(report.generated_at), "yyyy-MM-dd")}.pdf`;
      pdf.save(filename);
    } catch (err) {
      console.error("PDF generation failed", err);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      if (manageLoadingState) setDownloadingId(null);
    }
  };

  const deleteReport = async (id: number) => {
    if (!confirm("Delete this report? This cannot be undone.")) return;
    setDeletingId(id);
    try {
      await api(`/admin/reports/${id}`, "DELETE");
      setReports((prev) => prev.filter((r) => r.id !== id));
      if (selectedReport?.id === id) setSelectedReport(null);
    } catch (err) {
      console.error(err);
    } finally {
      setDeletingId(null);
    }
  };

  const sortedReports = [...reports].sort((a, b) => {
    let cmp = 0;
    if (sortField === "date") cmp = new Date(a.generated_at).getTime() - new Date(b.generated_at).getTime();
    else cmp = a.type.localeCompare(b.type);
    return sortDir === "asc" ? cmp : -cmp;
  });

  const toggleSort = (field: "date" | "type") => {
    if (sortField === field) setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    else { setSortField(field); setSortDir("desc"); }
  };

  const noData = <div className="text-sm text-muted-foreground py-8 text-center">No data in this range.</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold">Reports</h2>
          <p className="text-xs text-muted-foreground mt-0.5">Generate, filter, download and store platform reports</p>
        </div>
      </div>

      {/* Generate new report */}
      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Generate report</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap gap-3 items-end">
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">Type</p>
              <select value={filterType} onChange={e => setFilterType(e.target.value as "weekly" | "monthly" | "custom")}
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring">
                <option value="weekly">Weekly</option>
                <option value="monthly">Monthly</option>
                <option value="custom">Custom</option>
              </select>
            </div>
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">From</p>
              <input type="date" value={filterDateFrom} onChange={e => setFilterDateFrom(e.target.value)}
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring" />
            </div>
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">To</p>
              <input type="date" value={filterDateTo} onChange={e => setFilterDateTo(e.target.value)}
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring" />
            </div>
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">Category</p>
              <select value={filterCategory} onChange={e => setFilterCategory(e.target.value)}
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring">
                <option value="">All categories</option>
                {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">Region</p>
              <input type="text" value={filterRegion} onChange={e => setFilterRegion(e.target.value)} placeholder="e.g. Canada"
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring w-28" />
            </div>
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">Operator</p>
              <input type="text" value={filterOperator} onChange={e => setFilterOperator(e.target.value)} placeholder="Operator name"
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring w-32" />
            </div>
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">Manufacturer</p>
              <input type="text" value={filterManufacturer} onChange={e => setFilterManufacturer(e.target.value)} placeholder="Manufacturer"
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring w-32" />
            </div>
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">Product type</p>
              <input type="text" value={filterProductType} onChange={e => setFilterProductType(e.target.value)} placeholder="e.g. Berries"
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring w-28" />
            </div>
            <div>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-1">Listing type</p>
              <select value={filterListingType} onChange={e => setFilterListingType(e.target.value)}
                className="rounded-md border border-input bg-background px-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-ring">
                <option value="">All listings</option>
                <option value="capacity">Capacity only</option>
                <option value="product">Product only</option>
              </select>
            </div>
          </div>
          <Button onClick={generateReport} disabled={generating || !filterDateFrom || !filterDateTo}>
            {generating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <TrendingUp className="w-4 h-4 mr-2" />}
            {generating ? "Generating…" : "Generate Report"}
          </Button>
        </CardContent>
      </Card>

      {/* Report preview */}
      {selectedReport && selectedReport.data_json && (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <div>
              <CardTitle className="text-base font-semibold">{selectedReport.title}</CardTitle>
              <p className="text-xs text-muted-foreground mt-0.5">
                {format(new Date(selectedReport.date_range_start), "MMM d, yyyy")} – {format(new Date(selectedReport.date_range_end), "MMM d, yyyy")}
                {" · "}Generated by {selectedReport.generated_by_email} on {format(new Date(selectedReport.generated_at), "MMM d, yyyy")}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Button size="sm" variant="outline" onClick={() => downloadCSV(selectedReport)}>
                <Download className="w-3.5 h-3.5 mr-1.5" />
                Download CSV
              </Button>
              <Button size="sm" onClick={() => downloadPDF(selectedReport)} disabled={downloadingId === selectedReport.id}>
                {downloadingId === selectedReport.id
                  ? <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
                  : <FileDown className="w-3.5 h-3.5 mr-1.5" />}
                Download PDF
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div ref={reportPreviewRef} className="bg-white space-y-6 p-2">
              {selectedReport.data_json.summary && (
                <p className="text-sm text-muted-foreground border-l-4 border-primary pl-3">{selectedReport.data_json.summary}</p>
              )}

              {/* Sales volume KPIs */}
              {selectedReport.data_json.sales_volume && (
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  {[
                    { label: "Contracts", value: selectedReport.data_json.sales_volume.total_contracts.toLocaleString() },
                    { label: "Volume (kg)", value: selectedReport.data_json.sales_volume.total_quantity_kg.toLocaleString() },
                    { label: "Contract value", value: fmt(selectedReport.data_json.sales_volume.total_contract_value) },
                    { label: "Platform fees", value: fmt(selectedReport.data_json.sales_volume.platform_fees) },
                  ].map(s => (
                    <div key={s.label} className="rounded border p-3 text-center">
                      <div className="text-lg font-bold text-primary">{s.value}</div>
                      <div className="text-xs text-muted-foreground">{s.label}</div>
                    </div>
                  ))}
                </div>
              )}

              <div className="grid lg:grid-cols-2 gap-6">
                {/* Requests by month */}
                {selectedReport.data_json.requests_by_month && selectedReport.data_json.requests_by_month.length > 0 && (
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Requests over period</p>
                    <ResponsiveContainer width="100%" height={160}>
                      <BarChart data={selectedReport.data_json.requests_by_month}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                        <XAxis dataKey="month" tick={{ fontSize: 10 }} />
                        <YAxis allowDecimals={false} tick={{ fontSize: 10 }} />
                        <Tooltip />
                        <Bar dataKey="value" name="Requests" fill="#0F6E56" radius={[3, 3, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                )}

                {/* Bids by month */}
                {selectedReport.data_json.bids_by_month && selectedReport.data_json.bids_by_month.length > 0 && (
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Bids by month</p>
                    <ResponsiveContainer width="100%" height={160}>
                      <BarChart data={selectedReport.data_json.bids_by_month}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                        <XAxis dataKey="month" tick={{ fontSize: 10 }} />
                        <YAxis allowDecimals={false} tick={{ fontSize: 10 }} />
                        <Tooltip />
                        <Bar dataKey="value" name="Bids" fill="#0F6E56" radius={[3, 3, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                )}

                {/* Revenue by month */}
                {selectedReport.data_json.revenue_by_month && selectedReport.data_json.revenue_by_month.length > 0 && (
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Platform revenue (9% fees)</p>
                    <ResponsiveContainer width="100%" height={160}>
                      <LineChart data={selectedReport.data_json.revenue_by_month}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                        <XAxis dataKey="month" tick={{ fontSize: 10 }} />
                        <YAxis tick={{ fontSize: 10 }} tickFormatter={v => `$${v}`} />
                        <Tooltip formatter={(v: number) => fmt(v)} />
                        <Line type="monotone" dataKey="value" name="Revenue" stroke="#0F6E56" strokeWidth={2} dot={{ r: 3 }} />
                      </LineChart>
                    </ResponsiveContainer>
                  </div>
                )}
              </div>

              {/* Top materials */}
              {selectedReport.data_json.top_materials && selectedReport.data_json.top_materials.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Top materials requested</p>
                  <ResponsiveContainer width="100%" height={160}>
                    <BarChart data={selectedReport.data_json.top_materials}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                      <XAxis dataKey="name" tick={{ fontSize: 9 }} />
                      <YAxis allowDecimals={false} tick={{ fontSize: 10 }} />
                      <Tooltip />
                      <Bar dataKey="value" name="Requests" fill="#6366f1" radius={[3, 3, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              )}

              {/* Avg price by category */}
              {selectedReport.data_json.avg_price_by_category && selectedReport.data_json.avg_price_by_category.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Avg price by category ($/kg)</p>
                  <div className="overflow-x-auto rounded border">
                    <table className="w-full text-xs">
                      <thead className="bg-muted/30 border-b">
                        <tr>
                          <th className="text-left px-3 py-2 font-semibold text-muted-foreground">Category</th>
                          <th className="text-right px-3 py-2 font-semibold text-muted-foreground">Avg $/kg</th>
                          <th className="text-right px-3 py-2 font-semibold text-muted-foreground">Data points</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y">
                        {selectedReport.data_json.avg_price_by_category.map(r => (
                          <tr key={r.category}>
                            <td className="px-3 py-2 font-medium">{r.category}</td>
                            <td className="px-3 py-2 text-right text-primary font-semibold">${r.avg_price.toFixed(2)}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{r.count}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {/* Operator win rates */}
              {selectedReport.data_json.operator_win_rates && selectedReport.data_json.operator_win_rates.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Operator win rates</p>
                  <ResponsiveContainer width="100%" height={160}>
                    <BarChart data={selectedReport.data_json.operator_win_rates} layout="vertical">
                      <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                      <XAxis type="number" domain={[0, 100]} tick={{ fontSize: 10 }} tickFormatter={v => `${v}%`} />
                      <YAxis dataKey="name" type="category" tick={{ fontSize: 9 }} width={80} />
                      <Tooltip formatter={(v: number) => `${v}%`} />
                      <Bar dataKey="win_rate" name="Win rate" fill="#f59e0b" radius={[0, 3, 3, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Report history */}
      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
            Report history ({reports.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="space-y-2">{[...Array(3)].map((_, i) => <Skeleton key={i} className="h-10 w-full" />)}</div>
          ) : reports.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <FileDown className="w-10 h-10 mx-auto mb-3 opacity-20" />
              <p className="text-sm">No reports generated yet.</p>
              <p className="text-xs mt-1">Use the form above to generate your first report.</p>
            </div>
          ) : (
            <div className="overflow-x-auto rounded-lg border">
              <table className="w-full text-sm">
                <thead className="bg-muted/40 border-b">
                  <tr>
                    <th className="px-3 py-2.5 text-left font-semibold text-muted-foreground whitespace-nowrap text-xs">Title</th>
                    <th className="px-3 py-2.5 text-left font-semibold text-muted-foreground whitespace-nowrap text-xs">
                      <button className="flex items-center gap-1 hover:text-foreground transition-colors" onClick={() => toggleSort("type")}>
                        Type {sortField === "type" ? (sortDir === "asc" ? "↑" : "↓") : <span className="opacity-30">↕</span>}
                      </button>
                    </th>
                    <th className="px-3 py-2.5 text-left font-semibold text-muted-foreground whitespace-nowrap text-xs">Date range</th>
                    <th className="px-3 py-2.5 text-left font-semibold text-muted-foreground whitespace-nowrap text-xs">
                      <button className="flex items-center gap-1 hover:text-foreground transition-colors" onClick={() => toggleSort("date")}>
                        Generated {sortField === "date" ? (sortDir === "asc" ? "↑" : "↓") : <span className="opacity-30">↕</span>}
                      </button>
                    </th>
                    <th className="px-3 py-2.5 text-left font-semibold text-muted-foreground whitespace-nowrap text-xs">By</th>
                    <th className="px-3 py-2.5 text-right font-semibold text-muted-foreground text-xs">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {sortedReports.map((r) => (
                    <tr key={r.id} className={`hover:bg-muted/20 transition-colors ${selectedReport?.id === r.id ? "bg-primary/5" : ""}`}>
                      <td className="px-3 py-2.5 font-medium max-w-[200px] truncate">{r.title}</td>
                      <td className="px-3 py-2.5">
                        <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-primary/10 text-primary">
                          {REPORT_TYPE_LABELS[r.type] ?? r.type}
                        </span>
                      </td>
                      <td className="px-3 py-2.5 text-muted-foreground text-xs whitespace-nowrap">
                        {format(new Date(r.date_range_start), "MMM d")} – {format(new Date(r.date_range_end), "MMM d, yyyy")}
                      </td>
                      <td className="px-3 py-2.5 text-muted-foreground text-xs whitespace-nowrap">
                        {format(new Date(r.generated_at), "MMM d, yyyy HH:mm")}
                      </td>
                      <td className="px-3 py-2.5 text-muted-foreground text-xs max-w-[120px] truncate">{r.generated_by_email}</td>
                      <td className="px-3 py-2.5 text-right">
                        <div className="flex items-center justify-end gap-1">
                          <Button size="sm" variant="ghost" className="h-7 px-2 text-xs"
                            onClick={() => loadAndView(r.id)}>
                            View
                          </Button>
                          <Button size="sm" variant="ghost" className="h-7 px-2 text-xs"
                            onClick={() => fetchAndDownload(r.id)}
                            disabled={downloadingId === r.id}>
                            {downloadingId === r.id
                              ? <Loader2 className="w-3 h-3 animate-spin" />
                              : <FileDown className="w-3 h-3" />}
                          </Button>
                          <Button size="sm" variant="ghost" className="h-7 px-2 text-xs text-destructive hover:text-destructive"
                            onClick={() => deleteReport(r.id)}
                            disabled={deletingId === r.id}>
                            {deletingId === r.id ? <Loader2 className="w-3 h-3 animate-spin" /> : <Trash2 className="w-3 h-3" />}
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
