import { Router, type IRouter } from "express";
import healthRouter from "./system/health";
import operatorsRouter from "./marketplace/operators";
import requestsRouter from "./marketplace/requests";
import bidsRouter from "./marketplace/bids";
import dashboardRouter from "./account/dashboard";
import roleDashboardRouter from "./account/role-dashboard";
import stripeRouter from "./payments/stripe";
import connectRouter from "./payments/connect";
import authRouter from "./account/auth";
import adminRouter from "./admin/admin";
import errorsRouter from "./system/errors";
import notificationsRouter from "./account/notifications";
import disputesRouter from "./marketplace/disputes";
import analyticsRouter from "./market-data/analytics";
import eventsRouter from "./market-data/events";
import trafficRouter from "./market-data/traffic";
import benchmarksRouter from "./market-data/benchmarks";
import productMarketRouter from "./marketplace/product-market";
import machineryRouter from "./marketplace/machinery";
import observationsRouter from "./market-data/observations";
import newsletterRouter from "./content/newsletter";
import storageRouter from "./system/storage";
import manufacturersRouter from "./marketplace/manufacturers";
import siteSettingsRouter from "./system/site-settings";
import blogRouter from "./content/blog";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(errorsRouter);
router.use(operatorsRouter);
router.use(requestsRouter);
router.use(bidsRouter);
router.use(dashboardRouter);
router.use(roleDashboardRouter);
router.use(stripeRouter);
router.use(connectRouter);
router.use(adminRouter);
router.use(notificationsRouter);
router.use(disputesRouter);
router.use(analyticsRouter);
router.use(eventsRouter);
router.use(trafficRouter);
router.use(benchmarksRouter);
router.use(productMarketRouter);
router.use(machineryRouter);
router.use(observationsRouter);
router.use(newsletterRouter);
router.use(storageRouter);
router.use(manufacturersRouter);
router.use(siteSettingsRouter);
router.use(blogRouter);

export default router;
