import { pgTable, serial, text, integer, real, boolean, timestamp, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Market price observations gathered OUTSIDE the platform.
 *
 * `price_data_points` records prices generated by LyoDex itself — it requires a
 * `bid_id`, a `request_id` and an `operator_id`, because every row is a real
 * quote submitted through the site. A price heard on a phone call, read off a
 * published rate card, or found in a trade publication has none of those, so it
 * had nowhere to live.
 *
 * This table is deliberately a SEPARATE table rather than nullable columns on
 * the existing one. The two kinds of data differ in ways that matter:
 *
 *   - Provenance. One is measured, the other is reported. Merging them would let
 *     a second-hand figure be published as a platform measurement — the exact
 *     failure this codebase spent a release removing.
 *   - Lifecycle. Platform rows are immutable history; observations get corrected,
 *     re-sourced, superseded and retired as the market moves.
 *   - Trust. Observations carry a confidence level and a named source. Platform
 *     rows do not need one — the platform IS the source.
 *
 * Keeping them apart makes "computed" versus "observed" a structural fact rather
 * than a boolean somebody has to remember to check.
 */

export const OBSERVATION_SOURCE_TYPES = [
  /** Operator told us directly (call, email, meeting). */
  "operator_reported",
  /** Buyer told us what they were quoted. */
  "buyer_reported",
  /** Published rate card, price list, or public website. */
  "published_rate_card",
  /** Industry report, trade publication, government trade data. */
  "industry_publication",
  /** Admin's own research or estimate — the weakest tier. */
  "admin_research",
] as const;

export const OBSERVATION_GRADES = [
  "food",
  "gmp_pharma",
  "nutraceutical",
  "pet_food",
  "cosmetic",
  "other",
] as const;

export const PRICE_UNITS = ["per_kg", "per_lb", "per_batch", "per_hour"] as const;

export const CONFIDENCE_LEVELS = ["high", "medium", "low"] as const;

export const marketObservationsTable = pgTable("market_observations", {
  id: serial("id").primaryKey(),

  // ── Where this figure came from ────────────────────────────────────────────
  source_type: text("source_type").notNull(),
  /** Who said it — company name, publication, or person. Never shown publicly. */
  source_detail: text("source_detail"),
  /** Link to the rate card or report, when the source is public. */
  source_url: text("source_url"),
  /**
   * How much to trust it:
   *   high   — named operator quoting their own current price
   *   medium — second-hand, or a range rather than a figure
   *   low    — inferred, dated, or an estimate
   */
  confidence: text("confidence").notNull().default("medium"),

  // ── What was priced ────────────────────────────────────────────────────────
  category: text("category").notNull(),
  grade: text("grade").notNull().default("food"),
  /** Free text: "strawberry powder", "whole blueberries", "probiotic culture". */
  product_detail: text("product_detail"),

  // ── The price ──────────────────────────────────────────────────────────────
  price_amount: real("price_amount").notNull(),
  price_unit: text("price_unit").notNull().default("per_kg"),
  currency: text("currency").notNull().default("CAD"),

  /**
   * Volume band the price applies to.
   *
   * This is the field that makes the table worth having. Reported Quebec
   * food-grade pricing runs $6/kg at 100 kg and above versus $8/kg below it —
   * a third of the price determined by batch size alone. An average that ignores
   * the band describes no real transaction.
   *
   * Null max means "and above".
   */
  volume_min_kg: real("volume_min_kg"),
  volume_max_kg: real("volume_max_kg"),

  // ── Where and when ─────────────────────────────────────────────────────────
  region: text("region"),
  country: text("country").notNull().default("CA"),
  /** When the price was valid — NOT when the row was created. */
  observed_at: timestamp("observed_at").notNull().defaultNow(),

  // ── Commercial context that moves price ────────────────────────────────────
  certifications_required: text("certifications_required").array().notNull().default([]),
  lead_time_days: integer("lead_time_days"),
  /** e.g. "rush order", "includes packaging", "excludes freight". */
  conditions: text("conditions"),

  // ── Optional links back to platform records ────────────────────────────────
  operator_id: integer("operator_id"),
  bid_id: integer("bid_id"),

  // ── Curation ───────────────────────────────────────────────────────────────
  /**
   * Off by default. An observation is published only after an admin has looked
   * at it — the public benchmark must never inherit whatever was last typed in.
   */
  included_in_public: boolean("included_in_public").notNull().default(false),
  /** Admin who reviewed it; null means unreviewed. */
  verified_by: integer("verified_by"),
  verified_at: timestamp("verified_at"),
  /** Internal only — never leaves the admin panel. */
  admin_notes: text("admin_notes"),

  created_at: timestamp("created_at").notNull().defaultNow(),
  updated_at: timestamp("updated_at").notNull().defaultNow(),
}, (table) => [
  // Public aggregation always filters on these three together.
  index("market_obs_public_idx").on(table.included_in_public, table.grade, table.category),
  index("market_obs_region_idx").on(table.country, table.region),
]);

export const insertMarketObservationSchema = createInsertSchema(marketObservationsTable).omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export type InsertMarketObservation = z.infer<typeof insertMarketObservationSchema>;
export type MarketObservation = typeof marketObservationsTable.$inferSelect;
export type ObservationSourceType = (typeof OBSERVATION_SOURCE_TYPES)[number];
export type ObservationGrade = (typeof OBSERVATION_GRADES)[number];
